### PR TITLE
Add uploadable user profile images

### LINKED ISSUE #117: figure out how profile & group images will work

### PR DESCRIPTION
**Pull request by taymonbeal**
It's not pretty (in particular we need to figure out how to restore the attractive form styling), but it works.

IMPORTANT PRODUCTION NOTE: This adds production dependencies on Azure Blob Storage and Azure Cache for Redis, along with environment variables to configure them.

Fixes #117.

### CODE REVIEW

**Comment by taymonbeal** [comment]
Yeah, we need to fix the HTML but we need to do it in a way that makes Django forms still work. I'll try applying `django-crispy-forms` but we might still need some frontend support on this. I'll let you know what the results wind up looking like.

**Comment by Manoj-nathwani** [comment]
Updated the above feedback to move bugs i was getting for not following your instructions 😅

1) Totally agree, i've never used it before, but i've seen `django-crispy-forms` recommended everywhere so we should deff move over to it.
2) For now can you update your code to conform to the current way of building forms so we can pass this PR through. We can then make a new PR & feature update for upgrading the way to do form templating. Also means we can go live straight away with this update. This is awesome 🏆

**Comment by taymonbeal** [comment]
I can try, it's not 100% straightforward because it's involving a new kind of form widget that we haven't used before.

**Comment by taymonbeal** [comment]
Applied changes, they seem to work.

**Comment by Manoj-nathwani** [comment]
@taymonbeal Happy for you to charge forward to merge & deploy this if you're happy it works fine locally for ya. What's happening with default profile too? This solves uploading photos, so I presume we should make another card for setting default images?

**Comment by taymonbeal** [comment]
We already have #61 open for that.

**Comment by Manoj-nathwani** [comment]
# 🏆 This is great 🏆

**Pull request merged**
